### ISSUE TITLE
无法运行：err TypeError: 'generator' object is not subscriptable

### ISSUE THREAD

**Issue by yihong0618** [bupticybee/ChineseAiDungeonChatGPT#1]
```
按照 README 运行 python example_story.py
```

![image](https://user-images.githubusercontent.com/15976103/205585412-8e03d7c7-e7bd-4c86-9da2-fe2aff64dfd8.png)

**Comment by bupticybee** [comment]
> ```
> 按照 README 运行 python example_story.py
> ```
> 
> btw, 你的这个项目提交是没有头像的，很可能用的公司账号 push 的。
> 
> 很可能忘了
> 
> ```
> git config user.name ....
> git config user.email ....
> ```
> 
> ![image](https://user-images.githubusercontent.com/15976103/205585412-8e03d7c7-e7bd-4c86-9da2-fe2aff64dfd8.png)

这个情况我也遇到过，目前还很头疼，不知道为什么会这样，你有兴趣看下么？因为我这边的代码加起来就40行，我寻思应该很好debug

**Comment by bupticybee** [comment]
这个问题偶现，而且和机器有关，不同机器表现不同，能确定的是如果使用自己申请的token就不会有问题

**Comment by yihong0618** [comment]
@bupticybee 感谢，猜测 token 验证了机器的 mac, 我申请个 token 试试。

**Comment by acheong08** [comment]
It has been fixed

**Comment by bupticybee** [comment]
> > 我淘宝买的openai账号
> 
> OpenAI 账号是免费的。

我知道，我的问题是我没有美国手机号，openai账号在中国是无法注册的，需要同时有美国ip和美国电话

**Comment by bupticybee** [comment]
> It has been fixed. Update with `pip3 install revChatGPT --upgrade`

Thanks， @yihong0618 麻烦看看升级后是否还有问题

**Comment by yihong0618** [comment]
@bupticybee 一样的报错。

**Comment by bupticybee** [comment]
> @bupticybee 一样的报错。

试试看 https://colab.research.google.com/github/bupticybee/ChineseAiDungeonChatGPT/blob/main/Example.ipynb colab上能不能运行？

**Comment by acheong08** [comment]
@yihong0618 Remember to update your token

**Comment by acheong08** [comment]
Working on improving error message

**Comment by acheong08** [comment]
@yihong0618 @bupticybee 
ChatGPT is down. The website is down.

**Comment by acheong08** [comment]
![image](https://user-images.githubusercontent.com/36258159/205607904-e36af13b-d412-41f0-ac30-84ef479e2a90.png)

**Comment by bupticybee** [comment]
> @yihong0618 @bupticybee ChatGPT is down. The website is down.



> ![image](https://user-images.githubusercontent.com/36258159/205607904-e36af13b-d412-41f0-ac30-84ef479e2a90.png)

So that's why, still amazed by how this LM perform. Thanks very much for the explain.

**Comment by yihong0618** [comment]
@bupticybee 这个没问题，感谢。猜测是 API 不稳定，我晚上好好试一试
![image](https://user-images.githubusercontent.com/15976103/205608062-5d5ad101-7151-44a4-932c-16c452235308.png)

**Comment by acheong08** [comment]
有些人的token无法用。有些人的却可以。

**Comment by bupticybee** [comment]
Ok, considered solved, closing. Reopen if necessary.
