### ISSUE TITLE
 Max retries exceeded with url: /api/auth/session 

### ISSUE THREAD

**Issue by TwinkleLee** [bupticybee/ChineseAiDungeonChatGPT#10]
完成 pip3 install revChatGPT --upgrade 后执行 python3 app.py 出现报错:
requests.exceptions.SSLError: HTTPSConnectionPool(host='chat.openai.com', port=443): Max retries exceeded with url: /api/auth/session (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

**Comment by TwinkleLee** [comment]
> openai的服务器这几天不太稳定，可能需要等等，或者你所在地区的网络连不上openai，最近听说有部分地区开始实施白名单机制，有可能是这个导致的。
主要已经用了梯子了，直接访问openai的网站是正常的。是因为openai对非web端访问做了特殊限制吗

**Comment by bupticybee** [comment]
> > openai的服务器这几天不太稳定，可能需要等等，或者你所在地区的网络连不上openai，最近听说有部分地区开始实施白名单机制，有可能是这个导致的。
> 
> 主要已经用了梯子了，直接访问openai的网站是正常的。是因为openai对非web端访问做了特殊限制吗

有，一直都有，而且一直在变

**Comment by bupticybee** [comment]
> > openai的服务器这几天不太稳定，可能需要等等，或者你所在地区的网络连不上openai，最近听说有部分地区开始实施白名单机制，有可能是这个导致的。
> 
> 主要已经用了梯子了，直接访问openai的网站是正常的。是因为openai对非web端访问做了特殊限制吗

不行的话你试试用colab打开？

**Comment by TwinkleLee** [comment]
找到原因了，开启代理后，urllib版本过低就会出现这个异常。升级urllib3==1.25.11后可以正常使用。

另外请问一下，如果想用自己的账号，config中的session_token应该从哪里获取？我在revChatGPT的git中没有找到相关说明

**Comment by bupticybee** [comment]
> 找到原因了，开启代理后，urllib版本过低就会出现这个异常。升级urllib3==1.25.11后可以正常使用。
> 
> 另外请问一下，如果想用自己的账号，config中的session_token应该从哪里获取？我在revChatGPT的git中没有找到相关说明

https://github.com/acheong08/ChatGPT/wiki/Setup#token-authentication

在这里可以找到
