### ISSUE TITLE
token是不能用了吗，拿不到数据了

### ISSUE THREAD

**Issue by FreeEye** [bupticybee/ChineseAiDungeonChatGPT#18]
<img width="814" alt="image" src="https://user-images.githubusercontent.com/19985492/206471612-ff954d5b-5586-4767-8094-631a1e8ef27b.png">

**Comment by bupticybee** [comment]
是呀最近token过期越来越快了，我今天看看如何解决

**Comment by bupticybee** [comment]
现在再试试？

**Comment by FreeEye** [comment]
需要更换新的token的吗

**Comment by FreeEye** [comment]
> 现在再试
用之前的token好像不行

**Comment by bupticybee** [comment]
> 需要更换新的token的吗

不需要？

**Comment by bupticybee** [comment]
哦哦这样子，可能得用自己的token试一下

**Comment by bupticybee** [comment]
因为现在token基本5分钟更新一次，非常蛋疼

**Comment by FreeEye** [comment]
> 

可以了，感谢

**Comment by bupticybee** [comment]
那我关闭issue了
