### ISSUE TITLE
有人和我一样吗chatgptpy下不了

### ISSUE THREAD

**Issue by CanadaLynx2** [bupticybee/ChineseAiDungeonChatGPT#19]
ERROR: Could not find a version that satisfies the requirement chatgptpy (from versions: none)
ERROR: No matching distribution found for chatgptpy

Pip和pip3都用了都不行

**Comment by CanadaLynx2** [comment]
使用这个解决了
pip install pychatgpt --upgrade

**Comment by bupticybee** [comment]
嗯嗯好的，那我关issue啦
