### ISSUE TITLE
望推荐

### ISSUE THREAD

**Issue by MexLinker** [bupticybee/ChineseAiDungeonChatGPT#24]
成功运行了你的项目，很好玩，想问问，有没有类似作者您这种操作简便，但是是英文的ai地牢捏？

**Comment by bupticybee** [comment]
https://aidungeon.io/ 可以玩ai dungeon本体？

**Comment by MexLinker** [comment]
> 

hhh，谢谢dalao，（你回复好快啊！～）

**Comment by bupticybee** [comment]
那我先close issue了

**Comment by MexLinker** [comment]
> 那我先close issue了

👌
