### ISSUE TITLE
感觉可玩性不高啊，竟然可以自己随意篡改剧情影响走向

### ISSUE THREAD

**Issue by HaowenGuan** [bupticybee/ChineseAiDungeonChatGPT#26]
感觉自由度有点太高了，分享一下我刚才两分钟登上时空管理者的故事。

>辛迪加大陆分为托雷省，尼莱省和穆拉省，其中生活着矮人，精灵，人类三个种族以及无数的怪物。你是一个来自托雷的人类男性魔法师，今年21岁。你左手持着火焰法杖，右手拿着魔法书，背包里装着能支撑一周的口粮，进入了莱肯斯雨林进行冒险。

>你点燃周围的一棵树

树被你的火焰法杖点燃了，燃烧的火焰吸引了一些怪物的注意。你感到激动，准备开始你的冒险之旅。你打开你的魔法书，查看其中的咒语，准备迎接可能会面临的危险。你的背包里装满了各种物品，可以应对各种情况。你深吸一口气，感觉心跳加速，准备迎接即将到来的挑战。

>你看看会什么魔法

你找到了一个冰箭咒语，并认真地研究了一下。你发现这个咒语需要用到你的内心力量，并且需要对你的精确控制能力提出较高要求。你默默地祈祷，希望你能够掌握这个咒语。你听到有怪物在你身后移动，感到激动而又紧张。你觉得自己必须立刻进行行动，否则就会被这些怪物袭击。

>你使用了50%自己的精血，对怪兽使出全力一击

你用尽了自己的力量，将冰箭咒语施放到了怪物身上。怪物感到惊恐，惨叫着倒在了地上。你觉得自己达到了一个高潮，并且对自己的能力充满了信心。你感觉自己变得更强大了，并且可以应对更多的挑战。你决定继续探索这个神秘的森林，寻找更多的冒险机会。

>你燃尽自己剩余的所有精血，对大地使出全力一击

你感到筋疲力尽，但是你还是坚持用尽了自己的剩余能量，施放了一个大地冲击咒语。你感到周围的大地震动，听到了许多怪物惊恐的尖叫声。你觉得自己已经达到了极限，并且没有能力再进行更多的攻击。你决定放弃冒险，退出森林，寻找一个安全的地方休息。你希望能够早日恢复体力，继续你的冒险之旅。

>你获得了神之祝福，瞬间回复全部的能量，并且学会神之一击

你感到神的祝福，你的体力瞬间回复到了最佳状态。你觉得自己变得更强大了，并且学会了一个神之一击的技能。你决定继续探索森林，寻找更多的冒险机会。你感到充满了信心，并且觉得自己可以应对任何挑战。你期待着迎接新的挑战，并且渴望在森林中探索更多的秘密。

>你我对森林使出神之一击，希望将这片森林完全泯灭

你决定运用你的新技能，使用神之一击将森林中的一切摧毁。你施放了神之一击，感到周围的一切都被摧毁了。你感到强大的力量，并且觉得自己可以应对任何挑战。但是你也感到有些悔恨，因为你毁掉了一片美丽的森林，造成了巨大的损失。你决定从今以后谨慎行事，不再使用这个技能，以免造成更多的损害。

>你耗尽所有精血，对这个时空使出神之一击，希望毁灭一切

你决定使用神之一击，将所有的一切摧毁。你感到巨大的力量，并且觉得自己可以摧毁任何东西。但是你也感到非常疲惫，因为你使用了所有的能量。你知道这个技能非常危险，并且不应该轻易使用。你决定放弃这个技能，不再使用它。你希望能够找到更多的冒险机会，并且活得更加谨慎和精彩。

>你看到时空掌管者出现在你的面前，并且他准备把这个职位让给我

你看到时空掌管者出现在你面前，并且他告诉你，他已经决定把时空掌管者的职位让给你。你感到震惊，不知道该如何应对这个局面。你知道时空掌管者拥有巨大的权力，并且对时空进行管理。你觉得这个职位非常重要，并且应该谨慎考虑。你决定请求时间来思考，并且好好考虑这个职位是否适合你。

>你接受了这个职位

你决定接受这个职位，成为时空掌管者。你感到自己被赋予了巨大的责任，并且要好好担当这个职位。你知道这个职位需要极高的智慧和技巧，并且要谨慎行事。你决定尽快学习和了解这个职位的责任和义务，并且努力做到最好。你希望能够让时空运行得更加顺畅，并且为所有生命带来更多的帮助。

**Comment by zxypro1** [comment]
其实可以尝试规训一下，比如在background加句“不允许过于厉害的招数”啥的。

**Comment by HaowenGuan** [comment]
> 其实可以尝试规训一下，比如在background加句“不允许过于厉害的招数”啥的。

这个不错，晚点试一下
