### ISSUE TITLE
执行命令后无反应

### ISSUE THREAD

**Issue by sherlockHlb** [bupticybee/ChineseAiDungeonChatGPT#29]
python3 example_story.py和python3 app.py都不会唤起APP..

**Comment by yudeng101** [comment]
我也遇到一样的问题，最大的问题就是控制台没有任何输出信息

**Comment by zxypro1** [comment]
可以截个图看看吗

**Comment by Pythonpa** [comment]
跑app.py的时候，提示ValueError: Error refreshing session: No email and password provided
必须要填入自己的openAI账号的邮箱和密码咯？

**Comment by zxypro1** [comment]
貌似revchatgpt更新之后出了一些变化。我看一下。

**Comment by zxypro1** [comment]
貌似是token过期了，我更新一下。

**Comment by zxypro1** [comment]
问题已修复，用`pip install revchatgpt --upgrade`把库升级到最新版本即可运行。 @Pythonpa

**Comment by hikoxy** [comment]
![截屏2022-12-11 22 54 21](https://user-images.githubusercontent.com/119286204/206910866-149d4e53-a19a-47d0-a7a3-702cbdf318c6.jpg)
我也遇到同样的问题，运行后控制台没有任何输出，python版本3.11.1

**Comment by bupticybee** [comment]
@sherlockHlb @Pythonpa  @yudeng101  @zxypro1 openai又更新了接口，最近接口非常不稳定，所以可能得时刻关注接口变化，我暂时更新了config文件，现在暂时项目用我的token可用。

这几天想要稳定运行仍需要时刻关注 https://github.com/acheong08/ChatGPT/wiki/Setup 按照里边的说明准备config.py

**Comment by bupticybee** [comment]
@zxypro1 而且现在openai还会检验token和ip的一致性，所以，我们的token理论上也不能分享给其他人使用了

**Comment by zxypro1** [comment]
而且貌似现在还用了cloudflare，那可能用tls登录也不行了。看看情况吧。

**Comment by zxypro1** [comment]
@hikoxy 有试过直接`python`运行吗？

**Comment by bupticybee** [comment]
> 了解。那看来以后应该只能用pychatgpt的帐号密码登陆了。

账号密码登陆现在也会check ip地址，token也会check，总之对于国内用户非常不友好了

**Comment by bupticybee** [comment]
closing
