### ISSUE TITLE
获取可以弄一个主神空间模式

### ISSUE THREAD

**Issue by aadd445aadda** [bupticybee/ChineseAiDungeonChatGPT#3]
我觉得这个非常好玩，或者可以弄一个类型无限恐怖的主神空间一样的模式，每次人物的技能装备什么的生成一些种子数之类的保存下来，然后ai读取存档一样，但是这个设定我不知道怎么跟ai描述

**Comment by bupticybee** [comment]
有想法可以直接改代码呀，我就40行代码

**Comment by bupticybee** [comment]
暂时关闭，有需要再open
