### ISSUE TITLE
无法安装依赖

### ISSUE THREAD

**Issue by LamHuang** [bupticybee/ChineseAiDungeonChatGPT#34]
ERROR: Could not find a version that satisfies the requirement chatgptpy (from -r requirements.txt (line 2)) (from versions: none)
ERROR: No matching distribution found for chatgptpy (from -r requirements.txt (line 2))
试过换源和延迟时间也不得行

**Comment by bupticybee** [comment]
> ERROR: Could not find a version that satisfies the requirement chatgptpy (from -r requirements.txt (line 2)) (from versions: none) ERROR: No matching distribution found for chatgptpy (from -r requirements.txt (line 2)) 试过换源和延迟时间也不得行

因为这个依赖是python3.9才能够安装的，python版本不够新是没法安装的，如果不想更新py版本，也可以运行example_story.py，只是说没法使用部分特性

**Comment by bupticybee** [comment]
也就是说chatgptpy 可以不安装

**Comment by bupticybee** [comment]
closing
