### ISSUE TITLE
python3 example_story.py报错

### ISSUE THREAD

**Issue by BestJarvan** [bupticybee/ChineseAiDungeonChatGPT#35]
复现步骤
1. 安装依赖 ❯ `sudo pip3 install -r requirements.txt`
2. 修改config.py文件，替换`cf_clearance`和`session_token`
3. 运行`python3 example_story.py`
![image](https://user-images.githubusercontent.com/24928962/207001698-e3d0354e-4ac7-4d4e-8d3e-737d1ef15896.png)

**Comment by bupticybee** [comment]
> 复现步骤
> 
> 1. 安装依赖 ❯ `sudo pip3 install -r requirements.txt`
> 2. 修改config.py文件，替换`cf_clearance`和`session_token`
> 3. 运行`python3 example_story.py`
>    ![image](https://user-images.githubusercontent.com/24928962/207001698-e3d0354e-4ac7-4d4e-8d3e-737d1ef15896.png)

这个问题是因为openai这几天开始严查api接入，现在只能够通过挂vpn自己获取token，然后填写到config中，已经无法使用其他人的token登陆，并且调用保持在和登陆相同vpn条件下才能调用。

由于openai保持了非常高的api变动频率，所以现在也不保证获取自己的vpn就100%没问题，这只是我今天上午发现有效的方法。

**Comment by badounan** [comment]
兄台，你能自己搭建一个chatGPT的服务端吗？

**Comment by bupticybee** [comment]
> 兄台，你能自己搭建一个chatGPT的服务端吗？

并不行，openai没有开源模型
