### ISSUE TITLE
example_story.py和app.pyd

### ISSUE THREAD

**Issue by ZhangChen009** [bupticybee/ChineseAiDungeonChatGPT#36]
<img width="1440" alt="截屏2022-12-15 21 06 43" src="https://user-images.githubusercontent.com/78025139/207866748-2785f5dc-fb4b-4ad5-807a-e3ad15ce0166.png">

pychatgpt包显示已经装成功了，仍报错

<img width="1440" alt="截屏2022-12-15 21 06 58" src="https://user-images.githubusercontent.com/78025139/207867031-b05760cb-f36f-4434-bcd3-234ed7a67dbf.png">

**Comment by bupticybee** [comment]
1. pychatgpt要么是没安装好，要么是安装到了错误的python上
2. openai最近封禁了api调用方式，所以现在也比较难使用api连接上

**Comment by bupticybee** [comment]
暂时close，需要的话再open
