### ISSUE TITLE
完全弄不明白怎么玩，里面的各种什么什么.PY一个都打不开诶

### ISSUE THREAD

**Issue by xiaoyanmiao** [bupticybee/ChineseAiDungeonChatGPT#37]
一点开就出现个黑框然后瞬间消失，怎么回事

**Comment by bupticybee** [comment]
可能需要一些python知识才能运行起来，sorry，现在对一般用户还不太友好

**Comment by SameIe** [comment]
一样不会搞，等你完善更好，或如果可以出个教程？我也不知道哪里不对反正下了python，接着就不知道怎搞了。把那些代码输入全部没效果。

**Comment by bupticybee** [comment]
> 



> 一样不会搞，等你完善更好，或如果可以出个教程？我也不知道哪里不对反正下了python，接着就不知道怎搞了。把那些代码输入全部没效果。

嗯，不仅如此，现在openai对接口做了非常严格的限制，项目现在还在等待openai的接口稳定，暂时可以先等等

**Comment by niudage** [comment]
i don't know  i am very sorry
