### ISSUE TITLE
ModuleNotFoundError: No module named 'revChatGPT.revChatGPT'

### ISSUE THREAD

**Issue by jonsen-liu** [bupticybee/ChineseAiDungeonChatGPT#39]
已经install过了，
python app.py

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ChineseAiDungeonChatGPT\app.py", line 8, in <module>
    from story import StoryTeller
  File "C:\Users\Administrator\Desktop\ChineseAiDungeonChatGPT\story.py", line 1, in <module>
    from revChatGPT.revChatGPT import Chatbot
ModuleNotFoundError: No module named 'revChatGPT.revChatGPT'

**Comment by bupticybee** [comment]
最近可能第三方库也变化了，我没更新工程，所以导致了这个问题，有兴趣可以看下第三方库的具体变化尝试解决。

**Comment by jonsen-liu** [comment]
我对python不太了解，不过我尝试了下，revChatGPT.revChatGPT 改为 revChatGPT.official  没有报错了，但是通过session_token登录提示登陆失败，让账户密码登陆

**Comment by bupticybee** [comment]
> 我对python不太了解，不过我尝试了下，revChatGPT.revChatGPT 改为 revChatGPT.official 没有报错了，但是通过session_token登录提示登陆失败，让账户密码登陆

是的，openai对接口做了限制，需要使用自己的账户和token了现在

**Comment by jonsen-liu** [comment]
我是用的自己的session_token

**Comment by bupticybee** [comment]
> 我是用的自己的session_token

你可以参考下revChatGPT这个项目文档，可能后来登陆方式又有变化？我很久没有跟进了

**Comment by 412111959** [comment]
@jonsen-liu 
网上看到的,好像挂了
[revChatGPT](https://github.com/acheong08/ChatGPT/blob/main/src/revChatGPT/revChatGPT.py)仓库已经归档，基于逆向API的bot基本上挂掉了。

**Comment by moskalukigor** [comment]
> @jonsen-liu 网上看到的,好像挂了 [revChatGPT](https://github.com/acheong08/ChatGPT/blob/main/src/revChatGPT/revChatGPT.py)仓库已经归档，基于逆向API的bot基本上挂掉了。

You can use this module https://github.com/acheong08/ChatGPT

**Comment by 412111959** [comment]
@moskalukigor 
thank you 👍

**Comment by bupticybee** [comment]
Considered solved, closing. Reopen if necessary.
