### ISSUE TITLE
Your authentication token has expired

### ISSUE THREAD

**Issue by shaomai00** [bupticybee/ChineseAiDungeonChatGPT#4]
Error: 
{"detail":{"message":"Your authentication token has expired. Please try signing in again.","type":"invalid_request_error","param":null,"code":"token_expired"}}

**Comment by acheong08** [comment]
email/password authentication now supported @bupticybee. Check the updated docs on ChatGPT

**Comment by bupticybee** [comment]
> email/password authentication now supported @bupticybee. Check the updated docs on ChatGPT

ok thx

**Comment by bupticybee** [comment]
> email/password authentication now supported @bupticybee. Check the updated docs on ChatGPT

I see you keep the legacy login way now, it's great, from my view, it's safer.

**Comment by bupticybee** [comment]
Seems the token has to be updated every few hour, I currently don't want to set my account and pwd in config file in this project, so the plan is that I will keep update the token for a few days maybe and stop updating, project users might have to use their own token instead.

**Comment by acheong08** [comment]
> Seems the token has to be updated every few hour, I currently don't want to set my account and pwd in config file in this project, so the plan is that I will keep update the token for a few days maybe and stop updating, project users might have to use their own token instead.

That is recommended for public services yes

**Comment by bupticybee** [comment]
Considered solved, reopen if necessary.
