### ISSUE TITLE
Error refreshing session

### ISSUE THREAD

**Issue by Vi-jay** [bupticybee/ChineseAiDungeonChatGPT#9]
Error refreshing session
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body { font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px 0px }#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>Microsoft</title></head><body><div id='content'><div id='message'><h2>The request is blocked.</h2></div><div id='errorref'><span>05PmOYwAAAACidnVoE5qaQ5D92EjPNlsaSEtCRURHRTA5MTIAZTY2YjhiMDMtMDc5My00NDA5LTk3NzMtMmU2MTJlNzFhMWUz</span></div></div></body></html>

**Comment by Vi-jay** [comment]
请问这个怎么解决

**Comment by bupticybee** [comment]
最好的解决方式就是readme里边提到的，自己注册一个openai账号，然后把token填进config.py去

**Comment by Vi-jay** [comment]
> 最好的解决方式就是readme里边提到的，自己注册一个openai账号，然后把token填进config.py去

好的 谢谢  做的非常厉害 感谢

**Comment by bupticybee** [comment]
关闭issue，如有必要可以重新开
